FROM node:22-alpine AS deps
WORKDIR /app
COPY agent/package*.json ./
RUN npm install

FROM deps AS build
COPY agent ./
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 4100
CMD ["node", "dist/server.js"]
