ssl_certificate /etc/letsencrypt/live/${HYPERVERSE_DOMAIN}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${HYPERVERSE_DOMAIN}/privkey.pem;
ssl_session_timeout 1d;
ssl_session_cache shared:HyperVerseSSL:10m;
ssl_session_tickets off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
